# Generated by Django 4.2.19 on 2025-04-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
