# Generated by Django 4.2.19 on 2025-04-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_studio', '0002_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/', verbose_name='Изображение работы'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео/проект'),
        ),
    ]
