# Generated by Django 4.2.19 on 2025-06-23 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_studio', '0003_customuser_avatar_portfolio_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AZExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('exam_date', models.DateTimeField(verbose_name='Дата проведения экзамена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exams/images/', verbose_name='Изображение (задание)')),
                ('is_public', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано')),
                ('students', models.ManyToManyField(blank=True, related_name='exams_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Студенты на экзамене')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
                'ordering': ['-exam_date'],
            },
        ),
    ]
